# 应用服务 WEB 访问端口
server.port=8080

mybatis.type-aliases-package=com.securityproject.exercise.entity

spring.datasource.url=jdbc:mysql://192.168.6.130:3306/ican?serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=246801qqqQQQ!

#mybatis.mapper-locations=classpath:com/lmh/blog_project/dao/*.xml

#mybatis-plus.type-enums-package=com.lmh.blog_project.enums

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

mybatis-plus.global-config.db-config.insert-strategy=not_null
mybatis-plus.global-config.db-config.update-strategy=not_null

# ?????????????? xml ??????
mybatis-plus.mapper-locations:classpath:mapper/*.xml
# ??????
mybatis-plus.type-aliases-package:com.ican.project.model.entity

spring.data.redis.host=192.168.6.130
spring.data.redis.port=6379
spring.data.redis.password=246801qqqQQQ!

# under are to be use (Final Value)
jwt-expire-minutes=5